services:
  db_recipes:
    restart: always
    image: postgres:16-alpine
    volumes:
      - /var/lib/tandoor/db:/var/lib/postgresql/data
    env_file:
      - ./.env

  web_recipes:
    restart: always
    image: vabene1111/recipes
    env_file:
      - ./.env
    volumes:
      - /var/lib/tandoor/staticfiles:/opt/recipes/staticfiles
      - /var/lib/tandoor/mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes